### ISSUE TITLE
resume-cli version 1.0.0

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-cli#170]
It seems that resume-cli also needs a new version with various features.

I think that any particular _major_ cli version should be tied to the same resume-schema version, hence v1.0.0 for both, but I'll need @thomasdavis to decide upon that.
- [ ] Add the ability to export/publish locally, #169.
- [ ] Easier way to add information to resume.json, #171.
- [ ] Ability to change the default theme, #127.
- [ ] Add unit tests (and test new additions, too), #99.
- [ ] Remove interactive menus, #100.
- [ ] Read resume from stdin, #81.
- [ ] Add markdown support, #40.
- [ ] Add update command to convert prior version of schema, #55.
- [ ] Crash on export error, instead of writing said error to a file, #90.
- [ ] Anything in jsonresume/resume-schema#197 that needs code changes.
- [x] Fix current unit tests.

In the meantime, this will be a collection of fixes/features I think should be added.

**Comment by chrisdotcode** [comment]
I also think that we should make a new branch for v1.0.0, instead of merging into the current stable.

**Comment by chrisdotcode** [comment]
Created branch v1.0.0.

**Comment by PeterDaveHello** [comment]
And we should fix the test first(#145).

**Comment by chrisdotcode** [comment]
Added.

**Comment by PeterDaveHello** [comment]
Fixed.

**Comment by thomasdavis** [comment]
I am working on patching all the broken stuff. Would love if we can recruit someone to write some extensive tests so this doesn't happen again.

**Comment by thomasdavis** [comment]
Oh just noticed tests is ticked off. I think we are missing a few as publish with password is currently broken.

**Comment by thomasdavis** [comment]
I also won't be committing to 1.0.0 for a bit, as some of this stuff needs to get shipped asap.

**Comment by astephen2** [comment]
I've been starting on a v1 rewrite of my own. I've been doing it in Typescript with unit tests to help avoid some of the broken master issues we've been having (some of which are my fault. sorry!). Check out the v1_ts branch

**Comment by thomasdavis** [comment]
Excellent work! Typescript implementation will be awesome!

The current CLI is so broken, I think as soon as yours has some basic functionality we can switch over to the 1.0.0 branch.

**Comment by astephen2** [comment]
The v1_ts branch has the init, export and test functions built. I'll get around to building in the registry stuff soon.

But, do we necessarily want the registry? It seems like there's a lot of interesting work that could be done without the registry.
